"""Shared domain models for ServerForge services."""

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field


class ChannelKind(StrEnum):
    """Supported Discord channel kinds."""

    text = "text"
    voice = "voice"
    stage = "stage"
    forum = "forum"


class Visibility(StrEnum):
    """Template visibility options."""

    private = "private"
    public = "public"
    marketplace = "marketplace"


class RoleSpec(BaseModel):
    """Serializable role definition."""

    name: str
    color: int = 0
    hoist: bool = False
    mentionable: bool = False
    permissions: int = 0


class ChannelSpec(BaseModel):
    """Serializable channel definition."""

    name: str
    kind: ChannelKind
    category: str | None = None
    topic: str | None = None
    position: int = 0
    slowmode_delay: int = 0
    permissions: dict[str, dict[str, bool | None]] = Field(default_factory=dict)


class CategorySpec(BaseModel):
    """Serializable category definition."""

    name: str
    position: int = 0
    permissions: dict[str, dict[str, bool | None]] = Field(default_factory=dict)


class EmojiSpec(BaseModel):
    """Serializable emoji definition."""

    name: str
    image_url: str


class StickerSpec(BaseModel):
    """Serializable sticker definition."""

    name: str
    description: str
    emoji: str
    image_url: str


class ServerPlan(BaseModel):
    """Complete server design plan generated by AI, templates, or backups."""

    name: str
    description: str
    theme: str = "custom"
    categories: list[CategorySpec] = Field(default_factory=list)
    channels: list[ChannelSpec] = Field(default_factory=list)
    roles: list[RoleSpec] = Field(default_factory=list)
    emojis: list[EmojiSpec] = Field(default_factory=list)
    stickers: list[StickerSpec] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


class BackupSnapshot(BaseModel):
    """Guild backup snapshot payload."""

    guild_id: int
    name: str
    channels: list[dict[str, Any]]
    roles: list[dict[str, Any]]
    emojis: list[dict[str, Any]]
    settings: dict[str, Any]


class ModerationAction(BaseModel):
    """Moderation action audit payload."""

    kind: Literal["ban", "kick", "timeout", "warn", "lockdown"]
    guild_id: int
    moderator_id: int
    target_id: int | None = None
    reason: str
